// Code generated by OpenAPI Generator (https://openapi-generator.tech);

/*
 * DotAAS Part 2 | HTTP/REST | Submodel Repository Service Specification
 *
 * The entire Submodel Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) 2023
 *
 * API version: V3.0.3_SSP-001
 * Contact: info@idtwin.org
 */

// Package api for the SubmodelRepositoryAPIAPI service
package api

import (
	"database/sql"
	"errors"
	"net/http"
	"time"

	"github.com/eclipse-basyx/basyx-go-components/internal/common"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/asyncbulk"
	gen "github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	persistencepostgresql "github.com/eclipse-basyx/basyx-go-components/internal/submodelrepository/persistence"
)

// SubmodelRepositoryAPIAPIService handles Submodel Repository HTTP API requests.
// Endpoint logic is split across responsibility-specific files in this package.
type SubmodelRepositoryAPIAPIService struct {
	submodelBackend persistencepostgresql.SubmodelDatabase
	asyncManager    *asyncbulk.Manager
}

const componentName = "SMREPO"

const (
	invocationDelegationQualifierType = "invocationDelegation"
	defaultDelegationTimeout          = 30 * time.Second
	defaultDelegationAsyncTTL         = 15 * time.Minute
	delegationAsyncTTLKey             = "SMREPO_DELEGATION_ASYNC_TTL"
	delegationTrustedHostsKey         = "SMREPO_DELEGATION_TRUSTED_HOSTS"
)

const (
	delegatedAsyncSubmodelIdentifierMetadataKey = "submodelIdentifier"
	delegatedAsyncIDShortPathMetadataKey        = "idShortPath"
)

// NewSubmodelRepositoryAPIAPIService creates a Submodel Repository API service.
func NewSubmodelRepositoryAPIAPIService(databaseBackend persistencepostgresql.SubmodelDatabase) *SubmodelRepositoryAPIAPIService {
	return &SubmodelRepositoryAPIAPIService{
		submodelBackend: databaseBackend,
		asyncManager:    asyncbulk.NewManager("SMREPO-ASYNC", parseDelegationAsyncTTL()),
	}
}

func newAPIErrorResponse(err error, status int, operation string, info string) gen.ImplResponse {
	if err == nil {
		err = errors.New(http.StatusText(status))
	}

	return common.NewErrorResponse(err, status, componentName, operation, info)
}

func isNotFoundError(err error) bool {
	return common.IsErrNotFound(err) || errors.Is(err, sql.ErrNoRows)
}

func decodeOptionalCursor(cursor string) (string, error) {
	if cursor == "" {
		return "", nil
	}

	decodedCursor, err := common.DecodeString(cursor)
	if err != nil {
		return "", err
	}

	return string(decodedCursor), nil
}

func invalidLevelResponse(operation string) gen.ImplResponse {
	return newAPIErrorResponse(errors.New("invalid level parameter"), http.StatusBadRequest, operation, "InvalidLevelParameter")
}
