name: Go Formatting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  gofmt:
    name: GoFmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Use the version in go.mod if present; otherwise pin a version
          go-version-file: go.mod
          cache: true

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Run goimports (formatting + imports)
        id: goimports-run
        run: |
          goimports -d cmd/ internal/ pkg/ > format_output.txt
          if [ -s format_output.txt ]; then
            echo "❌ Formatting/import issues found:"
            echo "Files that need formatting:"
            cat format_output.txt
            echo ""
            echo "💡 To fix these issues locally, run:"
            echo "  goimports -w cmd/ internal/ pkg/"
            exit 1
          else
            echo "✅ All Go files are properly formatted"
          fi

      - name: Format Check Output
        if: failure()
        run: |
          echo "::error::Go files are not properly formatted. Please run 'goimports -w cmd/ internal/ pkg/' locally and commit the changes."